// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.5
// source: calculator.proto

package calculator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Calculator_Add_FullMethodName             = "/calculator.Calculator/Add"
	Calculator_SendInstruction_FullMethodName = "/calculator.Calculator/SendInstruction"
)

// CalculatorClient is the client API for Calculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalculatorClient interface {
	Add(ctx context.Context, opts ...grpc.CallOption) (Calculator_AddClient, error)
	SendInstruction(ctx context.Context, opts ...grpc.CallOption) (Calculator_SendInstructionClient, error)
}

type calculatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculatorClient(cc grpc.ClientConnInterface) CalculatorClient {
	return &calculatorClient{cc}
}

func (c *calculatorClient) Add(ctx context.Context, opts ...grpc.CallOption) (Calculator_AddClient, error) {
	stream, err := c.cc.NewStream(ctx, &Calculator_ServiceDesc.Streams[0], Calculator_Add_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorAddClient{stream}
	return x, nil
}

type Calculator_AddClient interface {
	Send(*AddRequest) error
	Recv() (*AddResponse, error)
	grpc.ClientStream
}

type calculatorAddClient struct {
	grpc.ClientStream
}

func (x *calculatorAddClient) Send(m *AddRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorAddClient) Recv() (*AddResponse, error) {
	m := new(AddResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorClient) SendInstruction(ctx context.Context, opts ...grpc.CallOption) (Calculator_SendInstructionClient, error) {
	stream, err := c.cc.NewStream(ctx, &Calculator_ServiceDesc.Streams[1], Calculator_SendInstruction_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorSendInstructionClient{stream}
	return x, nil
}

type Calculator_SendInstructionClient interface {
	Send(*AddRequest) error
	Recv() (*InstructionResponse, error)
	grpc.ClientStream
}

type calculatorSendInstructionClient struct {
	grpc.ClientStream
}

func (x *calculatorSendInstructionClient) Send(m *AddRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorSendInstructionClient) Recv() (*InstructionResponse, error) {
	m := new(InstructionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculatorServer is the server API for Calculator service.
// All implementations must embed UnimplementedCalculatorServer
// for forward compatibility
type CalculatorServer interface {
	Add(Calculator_AddServer) error
	SendInstruction(Calculator_SendInstructionServer) error
	mustEmbedUnimplementedCalculatorServer()
}

// UnimplementedCalculatorServer must be embedded to have forward compatible implementations.
type UnimplementedCalculatorServer struct {
}

func (UnimplementedCalculatorServer) Add(Calculator_AddServer) error {
	return status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedCalculatorServer) SendInstruction(Calculator_SendInstructionServer) error {
	return status.Errorf(codes.Unimplemented, "method SendInstruction not implemented")
}
func (UnimplementedCalculatorServer) mustEmbedUnimplementedCalculatorServer() {}

// UnsafeCalculatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalculatorServer will
// result in compilation errors.
type UnsafeCalculatorServer interface {
	mustEmbedUnimplementedCalculatorServer()
}

func RegisterCalculatorServer(s grpc.ServiceRegistrar, srv CalculatorServer) {
	s.RegisterService(&Calculator_ServiceDesc, srv)
}

func _Calculator_Add_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServer).Add(&calculatorAddServer{stream})
}

type Calculator_AddServer interface {
	Send(*AddResponse) error
	Recv() (*AddRequest, error)
	grpc.ServerStream
}

type calculatorAddServer struct {
	grpc.ServerStream
}

func (x *calculatorAddServer) Send(m *AddResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorAddServer) Recv() (*AddRequest, error) {
	m := new(AddRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Calculator_SendInstruction_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServer).SendInstruction(&calculatorSendInstructionServer{stream})
}

type Calculator_SendInstructionServer interface {
	Send(*InstructionResponse) error
	Recv() (*AddRequest, error)
	grpc.ServerStream
}

type calculatorSendInstructionServer struct {
	grpc.ServerStream
}

func (x *calculatorSendInstructionServer) Send(m *InstructionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorSendInstructionServer) Recv() (*AddRequest, error) {
	m := new(AddRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Calculator_ServiceDesc is the grpc.ServiceDesc for Calculator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Calculator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.Calculator",
	HandlerType: (*CalculatorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Add",
			Handler:       _Calculator_Add_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SendInstruction",
			Handler:       _Calculator_SendInstruction_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "calculator.proto",
}
